### ISSUE TITLE
Add support for route groups

### ISSUE THREAD

**Issue by axlon** [LaraCrafts/laravel-geo-routes#10]
Pretty self explanatory, currently only single routes are supported

**Comment by yak0d3** [comment]
I am currently working on this and i have already pushed  the basic functionality to the `geo-groups` branch a few minutes ago, there is still a lot to improve, maybe even a whole change of logic, but for now, that's all i've got on mind so i went for it and i actually think that'll do good for a starter.
I also have not added tests yet, so if anyone has the time, that'll be very helpful if he adds them. Thanks!

**Comment by axlon** [comment]
@yak0d3 what's the status on this? I want to start development on this so could you show me what you have?

**Comment by yak0d3** [comment]
> 
> 
> @yak0d3 what's the status on this? I want to start development on this so could you show me what you have?

I apologize that i'm replying after a long time, but i have not noticed your comment.
As for the issue, this can be considered solved with PR #24
